isc.game.outdatedtank {
  game {
    window {
      cellSize = 10
    }

    map {
      name = "map1"
      terrainColor = "GREEN"
    }

    players = [
      {
        name = "Player 1"
        specificity = "Red"
        controls {
          moveUp = "w"
          moveDown = "s"
          moveLeft = "a"
          moveRight = "d"
          shoot = " "
          turretLeft = "q"
          turretRight = "e"
        }
      },
      {
        name = "Player 2"
        specificity = "Blue"
        controls {
          moveUp = "i"
          moveDown = "k"
          moveLeft = "j"
          moveRight = "l"
          shoot = "p"
          turretLeft = "u"
          turretRight = "o"
        }
      }
    ]

    specificities = [
     {
       name = "Blue"
       fireCooldown = 0
       ammoDamage = 150
       ammoBounceLeft = 5
       health = 100
     },
     {
       name = "Camo"
       fireCooldown = 0
       ammoDamage = 150
       ammoBounceLeft = 5
       health = 100
     },
     {
       name = "Desert"
       fireCooldown = 0
       ammoDamage = 150
       ammoBounceLeft = 5
       health = 100
     },
     {
       name = "Red"
       fireCooldown = 0
       ammoDamage = 150
       ammoBounceLeft = 5
       health = 100
     },
     {
       name = "Purple"
       fireCooldown = 0
       ammoDamage = 150
       ammoBounceLeft = 5
       health = 100
     }
    ]
  }
}
