isc.game.outdatedtank {
  game {
    window {
      cellSize = 10
    }

    map {
      name = "map1"
      terrainColor = "GREEN"
    }

    players = [
      {
        name = "Player 1"
        color = "BLUE"
        controls {
          moveUp = "W"
          moveDown = "S"
          moveLeft = "A"
          moveRight = "D"
          shoot = "SPACE"
          turretLeft = "Q"
          turretRight = "E"
        }
      },
      {
        name = "Player 2"
        color = "RED"
        controls {
          moveUp = "I"
          moveDown = "K"
          moveLeft = "J"
          moveRight = "L"
          shoot = "ENTER"
          turretLeft = "U"
          turretRight = "O"
        }
      }
    ]
  }
}
