isc.game.outdatedtank {
  game {
    window {
      cellSize = 10
    }

    map {
      name = "map1"
      terrainColor = "GREEN"
    }

    players = [
      {
        name = "Player 1"
        specificity = "Purple"
        controls {
          moveUp = "w"
          moveDown = "s"
          moveLeft = "a"
          moveRight = "d"
          shoot = " "
          turretLeft = "q"
          turretRight = "e"
        }
      },
      {
        name = "Player 2"
        specificity = "Camo"
        controls {
          moveUp = "i"
          moveDown = "k"
          moveLeft = "j"
          moveRight = "l"
          shoot = "p"
          turretLeft = "u"
          turretRight = "o"
        }
      }
    ]

    specificities = [
    {
      name = "Blue",
      fireCooldown = 800,
      ammoDamage = 150,
      ammoBounceLeft = 5,
      health = 300
    },
    {
      name = "Camo",
      fireCooldown = 500,
      ammoDamage = 140,
      ammoBounceLeft = 6,
      health = 250
    },
    {
      name = "Desert",
      fireCooldown = 900,
      ammoDamage = 170,
      ammoBounceLeft = 4,
      health = 400
    },
    {
      name = "Red",
      fireCooldown = 500,
      ammoDamage = 155,
      ammoBounceLeft = 5,
      health = 275
    },
    {
      name = "Purple",
      fireCooldown = 1200,
      ammoDamage = 200,
      ammoBounceLeft = 5,
      health = 500
    }
    ]
  }
}
